default:
    tags:
        - test

stages:
    - Build
    - Test

Dependencies:
    stage: Build
    script:
        - python -m install -r requirements.text

Testing:
    stage: Test
    script:
        - python3 manage.py test


