stages:
    - Build
    - Test
    - Deployment

Dependencies:
    stage: Build
    script:
        - python3 -m pip install -r requirements.txt

Testing:
    tags:
        - test
    stage: Test
    script:
        - python3 manage.py test
    variables:
        SHOPIFY_API_KEY:
            $SHOPIFY_API_KEY
        SHOPIFY_API_PASSWORD:
            $SHOPIFY_API_PASSWORD
        REPAIREL_API_KEY:
            $REPAIREL_API_KEY
        REPAIREL_API_PASSWORD:
            $REPAIREL_API_PASSWORD

Deploy:
    tags:
        - deploy
    stage: Deployment
    script:
        - echo "Do CD here"
