default:
    tags:
        - test

stages:
    - Build
    - Test

Dependencies:
    stage: Build
    script:
        - python3 -m pip install -r requirements.txt

Testing:
    stage: Test
    script:
        - python3 manage.py test
